---
title: "CISC482 - Lecture11"
subtitle: "Regression 2"
author: "Dr. Jeremy Castagno"
footer:  "[https://jeremybyu.github.io/intro-ds-website](https://jeremybyu.github.io/intro-ds-website/)"
logo: "../images/logo.png"
format: 
  revealjs: 
    theme: slides.scss
    transition: fade
    slide-number: true
    show-slide-number: all 
    chalkboard: true
    code-copy: false
    revealjs-plugins:
      - noswipe
editor: visual
execute:
  freeze: auto

---


```{python}
#| context: setup
#| include: false
import pandas as pd
import seaborn as sns 
import numpy as np
from sklearn.datasets import make_blobs
from palmerpenguins import load_penguins, load_penguins_raw
df = load_penguins()
sns.set_style('whitegrid')
sns.set_context("poster", font_scale=1.25)
np.set_printoptions(precision=1, suppress=True, formatter={'float_kind': "{:.1f}".format})
pd.options.display.float_format = '{:,.2f}'.format
np.random.seed(10)
```

# Class Business


## Schedule

- Topic Ideas - Should be turned in! Will grade soon!
- Reading 5-3: Mar 01 @ 12PM, Wednesday
- [HW4](https://colab.research.google.com/drive/1EdakWIOXLV-1UjUytpgKj6yHMbq-Pvz3?usp=sharing) - Mar 08 @ Midnight
- [Proposal](#project-proposal): Mar 22, Wednesday

## Today

- Assumptions of Linear Regression
- Multiple Linear Regression

## Assumptions


## Assumptions of Linear Regression

- $x$ and $y$ have a linear relationship.
- The residuals of the observations are independent.
- The **mean** of the residuals is 0 and the variance of the residuals is **constant**.
- The residuals are approximately normally distributed.


## Linear Relationship?

```{python}
noise = np.random.normal(loc=0, scale=3, size=30)
x = np.arange(30)
y = (1.5 * x + 4) + noise
ax = sns.regplot(x=x,y=y, ci=None)
```


## Residual Plot

```{python}
ax = sns.residplot(x=x,y=y)
```

## Independence of Error

- The distances from the regression line to the points (residuals) should generally be random.
- You **do not** want to see patterns
- Was the previous plot of residual showing patterns, or was it more or less random?

## Residual are independent? Bad

```{python}
y = (1.5 * x + 4) + np.sin(np.linspace(0, np.pi*2, 30)) * 2 + noise*0.1
ax = sns.residplot(x=x,y=y)
```


## Examples of Dependence

- Time dependence can often be assessed by analyzing the scatter plot of residuals over time.
- Spatial dependence can often be assessed by analyzing a map of where the data was collected along with further inspection of the residuals for spatial patterns.
- Dependencies between observational units must be assessed in context of the study.





